# Generated by Django 3.1.5 on 2021-01-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210114_1231'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='superadmin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='supportteam',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='password',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='supportteam',
            name='username',
        ),
    ]
