# Generated by Django 3.1.5 on 2021-01-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210114_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmin',
            options={'permissions': [('can_view_revenue', 'Can View Revenue'), ('can_view_app_usage', 'Can app Usage'), ('add_permission', 'Add Permission')]},
        ),
    ]
